### ISSUE TITLE
applying upsampling layer is not supported?!

### ISSUE THREAD

**Issue by arasharchor** [joeddav/devol#1]
Hi,

as mentioned in the ReadME. This can be applied to other problems. I would like to apply that on image segmentation which has upsampling layer as well as conv, dropout, relu activation function, but I think this is not possible to do so. I couldn't see a way to do that.

Best,

**Comment by joeddav** [comment]
The project was developed, initially at least, for image classification problems. So no, there's no support for upsampling layers. You might be able to modify 'genome_handler.py' to do what you're looking for. I'd also look at the metric you use as a basis for evaluating fitness, since currently it uses classification accuracy - maybe not as sensical for a detection problem.
