### ISSUE TITLE
Input shape

### ISSUE THREAD

**Issue by davidADSP** [joeddav/devol#26]
In genome_handler.py

`dim = min(self.input_shape[:-1]) # keep track of smallest dimension`

The `[:-1]` causes an error when the input is flat (i.e. not an image), as it tries to take a min over a empty variable.

For me changing to 

`dim = min(self.input_shape]) # keep track of smallest dimension`

fixed the issue.

**Comment by joeddav** [comment]
If that works for your current application, great, but any time you start doing multi-channel inputs that will run into issues. Since the setup is intended for image classification problems (including learning convolutional layers), the better workaround would probably be to add an empty dimension at the end of your input. E.g.

    data = np.atleast_2d(data).T
